name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  introduction_screen: ^3.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/onboarding/
  # fonts:
  #   - family: SF
  #     fonts:
  #       - asset: assets/fonts/SF-Pro-Display-Regular.otf
